version: "3.9"
services:

  frontend:
    image: ubuntu:latest
    volumes:
      - ./frontend:/app
    ports:
      - "50:5050"
    networks:
      - cnManagementNetwork
    hostname: cnManagement-frontend
    depends_on:
      - db
    stdin_open: true
    tty: true
    command:
      - bash
      - apt-get update

  backend:
    image: node:latest
    volumes:
      - ./backend:/app
    ports:
      - "81:8181"
    networks:
      - cnManagementNetwork
    hostname: cnManagement-node
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: mysql:latest
    environment:
      MYSQL_USER: cnSensei
      MYSQL_PASSWORD: cnSenseiUser
      MYSQL_ROOT_PASSWORD: cnManagementAdmin
      MYSQL_TCP_PORT: 7070
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/setup:/docker-entrypoint-initdb.d
    ports:
      - "70:7070"
    networks:
      - cnManagementNetwork
    hostname: cnManagement-mysql
    stdin_open: true
    tty: true

networks:
  cnManagementNetwork: